### PR TITLE
bug #22 CoreBundle check if domain has content types fixes #22

### LINKED ISSUE #22: Move ApiKey to Organization level
At the moment there are Users and ApiClients that are managed per organization (after implementing https://github.com/unite-cms/unite-cms/issues/20). They only have an identifier and roles. 

In the future we probably need a way other individuals can authenticate against the api (via oauth) and also fields on each of this user entities.

### PR DESCRIPTION
**Pull request by stefan-kamsker**

### CODE REVIEW

File: src/Bundle/CoreBundle/Controller/GraphQLApiController.php [hunk 1]
```diff
@@ -15,6 +15,7 @@
 use UnitedCMS\CoreBundle\Entity\Domain;
 use UnitedCMS\CoreBundle\Entity\Organization;
 
+
```
Comment (franzwilding) [inline src/Bundle/CoreBundle/Controller/GraphQLApiController.php]: Remove 2nd newline

File: src/Bundle/CoreBundle/Controller/GraphQLApiController.php [hunk 2]
```diff
@@ -34,12 +35,13 @@ public function indexAction(Organization $organization, Domain $domain, Request
         $schema = new Schema(
             [
                 'query' => $schemaTypeManager->getSchemaType('Query'),
-                'mutation' => $schemaTypeManager->getSchemaType('Mutation'),
+                'mutation' => ($domain->hasContentTypes()) ? $schemaTypeManager->getSchemaType('Mutation'):NULL,
```
Comment (franzwilding) [inline src/Bundle/CoreBundle/Controller/GraphQLApiController.php]: you should also check for ContentTypes. Maybe give the domain a method hasDefinedTypes() or hasContentOrSettingTypes()

File: src/Bundle/CoreBundle/Entity/Domain.php [hunk 3]
```diff
@@ -136,6 +136,17 @@ public function __construct()
         $this->apiClients = new ArrayCollection();
     }
 
+    /**
+     *  checks if domain has content types
+     */
+    public function hasContentTypes() {
+        if ($this->getContentTypes()->count() > 0)
+        {
```
Comment (franzwilding) [inline src/Bundle/CoreBundle/Entity/Domain.php]: Opening bracket can be on same line with if statement

File: src/Bundle/CoreBundle/Entity/Domain.php [hunk 4]
```diff
@@ -136,6 +136,17 @@ public function __construct()
         $this->apiClients = new ArrayCollection();
     }
 
+    /**
+     *  checks if domain has content types
```
Comment (franzwilding) [inline src/Bundle/CoreBundle/Entity/Domain.php]: Add @return type to php doc
